### ISSUE TITLE
Add source data note to tools and reports

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-documentation#23]
Users have requested a source note for data products and tools. 

Adding a note similar to "These reports are derived from the HMDA static datasets" will satisfy this request.

**Comment by Kibrael** [comment]
- Aggregate Reports
- Disclosure Reports
- Data Browser
- others?

**Comment by MattPerrine** [comment]
@Kibrael - I'm good with this and with the minor updates Chynna made. Let's get this into Dev to take a look.

**Comment by wpears** [comment]
Closed by https://github.com/cfpb/hmda-pub-ui/commit/e7be5eab037aeb748222586b2a4fa4028fb5e5bc and 9958ab8f8dd109218f57ec54cbd322077aca2ee1
